version: "3.3"
services:
  database:
    image: mysql:8.0
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: .
    command: start
    env_file:
      - app.env
    ports:
      - 8080:8080
    depends_on:
      - database
volumes:
  database-data:
